version: '3.6'
services:
  postgres:
    build: .
    container_name: postgres-db
    ports:
      - '5431:5432'
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./output:/tmp/output
    env_file: .env

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - '3307:3306'
    volumes:
      - /var/lib/mysql
      - ./input:/docker-entrypoint-initdb.d
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:
